name: full_chat_firebase
description: A new Flutter project.


publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  firebase_core: ^1.23.0
  firebase_auth: ^3.10.0
  cloud_firestore: ^3.4.9
  firebase_storage: ^10.3.9
  country_picker: ^2.0.16
  flutter_riverpod: ^2.0.0-dev.9
  image_picker: ^0.8.5+3

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true


  assets:
    - assets/images/

